version: "3.8"

services:
  api_gateway:
    image: api_gateway
    container_name: api_gateway
    hostname: api_gateway
    build:
      context: ./api-gateway/
      dockerfile: Dockerfile
    restart: always
    environment:
      ACCOMMODATION_SERVICE_ADDRESS: accommodation_service${ACCOMMODATION_SERVICE_ADDRESS}
      BOOKING_SERVICE_ADDRESS: booking_service${BOOKING_SERVICE_ADDRESS}
      GATEWAY_ADDRESS: ${GATEWAY_ADDRESS}
    depends_on:
      - accommodation_service
      - booking_service
    ports:
      - "11000:11000"

  accommodation_service:
    image: accommodation_service
    container_name: accommodation_service
    hostname: accommodation_service
    build:
      context: accommodation-service/
      dockerfile: Dockerfile
    restart: always
    environment:
      ACCOMMODATION_SERVICE_ADDRESS: ${ACCOMMODATION_SERVICE_ADDRESS}
      ACCOMMODATION_DATABASE_ADDRESS: accommodation_database:5432
      ACCOMMODATION_DATABASE_USERNAME: ${ACCOMMODATION_DATABASE_USERNAME}
      ACCOMMODATION_DATABASE_PASSWORD: ${ACCOMMODATION_DATABASE_PASSWORD}
    depends_on:
      - accommodation_database

  accommodation_database:
    image: postgres:15.0-alpine
    container_name: accommodation_database
    hostname: accommodation_database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '12102:5432'
    restart: always

  booking_service:
    image: booking_service
    container_name: booking_service
    hostname: booking_service
    build:
      context: booking-service/
      dockerfile: Dockerfile
    restart: always
    environment:
      BOOKING_SERVICE_ADDRESS: ${BOOKING_SERVICE_ADDRESS}

#  public_app:
#    image: public_app
#    container_name: public_app
#    hostname: public_app
#    build:
#      context: ./public-app/.
#      dockerfile: Dockerfile
#    ports:
#      - "10000:10000"
#    restart: always
#    depends_on:
#      - api_gateway